### ISSUE TITLE
Function prototype might no be enough 

### ISSUE THREAD

**Issue by tomMoulard** [SidoShiro/Shell_Color#1]
I think that:

https://github.com/SidoShiro/Shell_Color/blob/56417df3500d571d339797778bfd0e90491c758c/color.go#L16

Is not a good enough function prototype just taking a string as argument because the [fmt function](https://godoc.org/fmt#Println)  is a lot more robust. You might wana do something like the [log package](https://godoc.org/log) ([source](https://golang.org/src/log/log.go)). 
Where the function `log.Println` call `fmt.Println` like this
```golang
// Println calls l.Output to print to the logger.
// Arguments are handled in the manner of fmt.Println.
func (l *Logger) Println(v ...interface{}) { l.Output(2, fmt.Sprintln(v...)) }
```

**Comment by SidoShiro** [comment]
hmmm... I'm very new to Go....
I need to learn more about it....
